### ISSUE TITLE
As a player, I’d like to be presented with a title screen and then be able to select how many players there are, so that I can play the game in multiple configurations.

### ISSUE THREAD

**Issue by nflanagan6** [nflanagan6/cardgame#10]

**Comment by abbiland** [comment]
User interface, can use JavaFX buttons if we want or just have user select from options, menu, or enter. From UI, take in the number of players. Note that if > 4, we have to use shoe of two decks. See story 11 https://github.com/nflanagan6/cardgame/projects/1#card-80564358
