### ISSUE TITLE
As a player, on each turn, I should be asked to draw a card from the draw pile or discard pile, be shown the card, and then allowed to select what card to replace, so that I can take my turn.

### ISSUE THREAD

**Issue by nflanagan6** [nflanagan6/cardgame#14]

**Comment by abbiland** [comment]
For each turn, prompt user to draw card from either draw or discard pile. Display card to the user. All card arrays are stored - the draw, discard, players - will be used to present proper cards to user. User can select what card to replace --- with restriction, if card is from top of discard pile; See story 15: https://github.com/nflanagan6/cardgame/projects/1#card-80564378
On each turn, also need to have the game present other things to the user as well. See story 13: https://github.com/nflanagan6/cardgame/projects/1#card-80564365
